document.getElementById('realizarcv').addEventListener('click', function(){
    let nomcv = document.getElementById('nombrecv').value;
    console.log("El nombre es "+nomcv);
    let apecv = document.getElementById('apellidocv').value;
    console.log("El apellido es "+apecv);
    let anicv = document.getElementById('anioscv').value;
    console.log("Cantidad de años es "+anicv);
    let dircv = document.getElementById('direccioncv').value;
    console.log("La dirección es "+dircv);
    let ciucv = document.getElementById('ciudadcv').value;
    console.log("La ciudad es "+ciucv);
    let celcv = document.getElementById('celularcv').value;
    console.log("El número de celular es "+celcv);
    let corcv = document.getElementById('correocv').value;
    console.log("El correo electrónico es "+corcv);
    let tralugar1 = document.getElementById('trabajolugar1').value;
    console.log("El lugar del trabajo es "+tralugar1);
    let trafechain1 = document.getElementById('trabajofechain1').value;
    console.log("El fecha inicial del trabajo es "+trafechain1);
    let trafechafi1 = document.getElementById('trabajofechafi1').value;
    console.log("El fecha final del trabajo es "+trafechafi1);
    let puecv1 = document.getElementById('puestocv1').value;
    console.log("El puesto de trabajo es "+puecv1);
    let tarcv10 = document.getElementById('tareacv10').value;
    console.log("La tarea a realizar es "+tarcv10);
    let tarcv11 = document.getElementById('tareacv11').value;
    console.log("La tarea a realizar es "+tarcv11);
    let tarcv12 = document.getElementById('tareacv12').value;
    console.log("La tarea a realizar es "+tarcv12);
    let tarcv13 = document.getElementById('tareacv13').value;
    console.log("La tarea a realizar es "+tarcv13);
        let tralugar2 = document.getElementById('trabajolugar2').value;
        console.log("El 2do lugar del trabajo es "+tralugar2);
        let trafechain2 = document.getElementById('trabajofechain2').value;
        console.log("El fecha inicial del 2do trabajo es "+trafechain2);
        let trafechafi2 = document.getElementById('trabajofechafi2').value;
        console.log("El fecha final del 2do trabajo es "+trafechafi2);
        let puecv2 = document.getElementById('puestocv2').value;
        console.log("El puesto del 2do trabajo es "+puecv2);
        let tarcv20 = document.getElementById('tareacv20').value;
        console.log("La tarea a realizar es "+tarcv20);
        let tarcv21 = document.getElementById('tareacv21').value;
        console.log("La tarea a realizar es "+tarcv21);
        let tarcv22 = document.getElementById('tareacv22').value;
        console.log("La tarea a realizar es "+tarcv22);
        let tarcv23 = document.getElementById('tareacv23').value;
        console.log("La tarea a realizar es "+tarcv23);
            let tralugar3 = document.getElementById('trabajolugar3').value;
            console.log("El 3do lugar del trabajo es "+tralugar3);
            let trafechain3 = document.getElementById('trabajofechain3').value;
            console.log("El fecha inicial del 3do trabajo es "+trafechain3);
            let trafechafi3 = document.getElementById('trabajofechafi3').value;
            console.log("El fecha final del 3do trabajo es "+trafechafi3);
            let puecv3 = document.getElementById('puestocv3').value;
            console.log("El puesto del 3do trabajo es "+puecv3);
            let tarcv30 = document.getElementById('tareacv30').value;
            console.log("La tarea a realizar es "+tarcv30);
            let tarcv31 = document.getElementById('tareacv31').value;
            console.log("La tarea a realizar es "+tarcv31);
            let tarcv32 = document.getElementById('tareacv32').value;
            console.log("La tarea a realizar es "+tarcv32);
            let tarcv33 = document.getElementById('tareacv33').value;
            console.log("La tarea a realizar es "+tarcv33);        
    let estlugar1 = document.getElementById('estudiolugar1').value;
    console.log("Se realizó la cursada en "+estlugar1);
    let curfechain1 = document.getElementById('cursofechain1').value;
    console.log("La cursada inició el "+curfechain1);
    let curfechafi1 = document.getElementById('cursofechafi1').value;
    console.log("La cursada finalizó el "+curfechafi1);
    let titcv1 = document.getElementById('titulocv1').value;
    console.log("Recibió el títitulo de "+titcv1);
        let estlugar2 = document.getElementById('estudiolugar2').value;
        console.log("Se realizó la 2da cursada en "+estlugar2);
        let curfechain2 = document.getElementById('cursofechain2').value;
        console.log("La cursada inició el "+curfechain2);
        let curfechafi2 = document.getElementById('cursofechafi2').value;
        console.log("La cursada finalizó el "+curfechafi2);
        let titcv2 = document.getElementById('titulocv2').value;
        console.log("Recibió el títitulo de "+titcv2);
            let estlugar3 = document.getElementById('estudiolugar3').value;
            console.log("Se realizó la 3ra cursada en "+estlugar3);
            let curfechain3 = document.getElementById('cursofechain3').value;
            console.log("La cursada inició el "+curfechain3);
            let curfechafi3 = document.getElementById('cursofechafi3').value;
            console.log("La cursada finalizó el "+curfechafi3);
            let titcv3 = document.getElementById('titulocv3').value;
            console.log("Recibió el títitulo de "+titcv3);
    let concv1 = document.getElementById('conocimientocv1').value;
    console.log("Sus conocimientos son "+concv1);
    let concv2 = document.getElementById('conocimientocv2').value;
    console.log("Sus conocimientos son "+concv2);
    let concv3 = document.getElementById('conocimientocv3').value;
    console.log("Sus conocimientos son "+concv3);
    let concv4 = document.getElementById('conocimientocv4').value;
    console.log("Sus conocimientos son "+concv4);
        
document.getElementById('nombreok').innerHTML = nomcv + " " + apecv;
document.getElementById('edadok').innerHTML = anicv + " años";
document.getElementById('direccionok').innerHTML = dircv + ", " + ciucv;
document.getElementById('celularok').innerHTML = celcv;
document.getElementById('correook').innerHTML = corcv;
    document.getElementById('trabajook1').innerHTML = tralugar1 + ", " + trafechain1 + " | " + trafechafi1;
    document.getElementById('puestook1').innerHTML = puecv1;
    document.getElementById('tareasok10').innerHTML = "° " + tarcv10;
    document.getElementById('tareasok11').innerHTML = "° " + tarcv11;
    document.getElementById('tareasok12').innerHTML = "° " + tarcv12;
    document.getElementById('tareasok13').innerHTML = "° " + tarcv13;
        document.getElementById('trabajook2').innerHTML = tralugar2 + ", " + trafechain2 + " | " + trafechafi2;
        document.getElementById('puestook2').innerHTML = puecv2;
        document.getElementById('tareasok20').innerHTML = "° " + tarcv20;
        document.getElementById('tareasok21').innerHTML = "° " + tarcv21;
        document.getElementById('tareasok22').innerHTML = "° " + tarcv22;
        document.getElementById('tareasok23').innerHTML = "° " + tarcv23;
            document.getElementById('trabajook3').innerHTML = tralugar3 + ", " + trafechain3 + " | " + trafechafi3;
            document.getElementById('puestook3').innerHTML = puecv3;
            document.getElementById('tareasok30').innerHTML = "° " + tarcv30;
            document.getElementById('tareasok31').innerHTML = "° " + tarcv31;
            document.getElementById('tareasok32').innerHTML = "° " + tarcv32;
            document.getElementById('tareasok33').innerHTML = "° " + tarcv33;
    document.getElementById('lugarok1').innerHTML = estlugar1 + ", " + curfechain1 + " | " + curfechafi1;
    document.getElementById('titulook1').innerHTML = titcv1;
        document.getElementById('lugarok2').innerHTML = estlugar2 + ", " + curfechain2 + " | " + curfechafi2;
        document.getElementById('titulook2').innerHTML = titcv2;
            document.getElementById('lugarok3').innerHTML = estlugar3 + ", " + curfechain3 + " | " + curfechafi3;
            document.getElementById('titulook3').innerHTML = titcv3;
    document.getElementById('conocimientook1').innerHTML = "° " + concv1;
    document.getElementById('conocimientook2').innerHTML = "° " + concv2;
    document.getElementById('conocimientook3').innerHTML = "° " + concv3;
    document.getElementById('conocimientook4').innerHTML = "° " + concv4;   

    document.getElementById('contenedorResultado').style.display = 'block';
    document.getElementById('botonescolor').style.display = 'block';
});

document.getElementById('colorblanco').addEventListener('click', function(){
    document.getElementById('nombreok').style.backgroundColor = 'rgb(120, 120, 120)';
    document.getElementById('experienciacv').style.backgroundColor = 'rgb(120, 120, 120)';
    document.getElementById('estudioscv').style.backgroundColor = 'rgb(120, 120, 120)';
    document.getElementById('conocimientoscv').style.backgroundColor = 'rgb(120, 120, 120)';
    document.getElementById('trabajook1').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('trabajook2').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('trabajook3').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('lugarok1').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('lugarok2').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('lugarok3').style.backgroundColor = 'rgb(160, 160, 160)';
    document.getElementById('puestook1').style.backgroundColor = 'rgb(200, 200, 200)';
    document.getElementById('puestook2').style.backgroundColor = 'rgb(200, 200, 200)';
    document.getElementById('puestook3').style.backgroundColor = 'rgb(200, 200, 200)';
    document.getElementById('contenedorResultado').style.backgroundColor = 'rgb(255, 255, 255)';
});

document.getElementById('colorrojo').addEventListener('click', function(){
    document.getElementById('nombreok').style.backgroundColor = 'rgb(230, 10, 10)';
    document.getElementById('experienciacv').style.backgroundColor = 'rgb(230, 10, 10)';
    document.getElementById('estudioscv').style.backgroundColor = 'rgb(230, 10, 10)';
    document.getElementById('conocimientoscv').style.backgroundColor = 'rgb(230, 10, 10)';
    document.getElementById('trabajook1').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('trabajook2').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('trabajook3').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('lugarok1').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('lugarok2').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('lugarok3').style.backgroundColor = 'rgb(255, 80, 80)';
    document.getElementById('puestook1').style.backgroundColor = 'rgb(255, 130, 130)';
    document.getElementById('puestook2').style.backgroundColor = 'rgb(255, 130, 130)';
    document.getElementById('puestook3').style.backgroundColor = 'rgb(255, 130, 130)';
    document.getElementById('contenedorResultado').style.backgroundColor = 'rgb(255, 200, 200)';
});
document.getElementById('colorverde').addEventListener('click', function(){
    document.getElementById('nombreok').style.backgroundColor = 'rgb(10, 170, 10)';
    document.getElementById('experienciacv').style.backgroundColor = 'rgb(10, 170, 10)';
    document.getElementById('estudioscv').style.backgroundColor = 'rgb(10, 170, 10)';
    document.getElementById('conocimientoscv').style.backgroundColor = 'rgb(10, 170, 10)';
    document.getElementById('trabajook1').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('trabajook2').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('trabajook3').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('lugarok1').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('lugarok2').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('lugarok3').style.backgroundColor = 'rgb(80, 255, 80)';
    document.getElementById('puestook1').style.backgroundColor = 'rgb(130, 255, 130)';
    document.getElementById('puestook2').style.backgroundColor = 'rgb(130, 255, 130)';
    document.getElementById('puestook3').style.backgroundColor = 'rgb(130, 255, 130)';
    document.getElementById('contenedorResultado').style.backgroundColor = 'rgb(200, 255, 200)';
});
document.getElementById('colorazul').addEventListener('click', function(){
    document.getElementById('nombreok').style.backgroundColor = 'rgb(10, 10, 220)';
    document.getElementById('experienciacv').style.backgroundColor = 'rgb(10, 10, 220)';
    document.getElementById('estudioscv').style.backgroundColor = 'rgb(10, 10, 220)';
    document.getElementById('conocimientoscv').style.backgroundColor = 'rgb(10, 10, 220)';
    document.getElementById('trabajook1').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('trabajook2').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('trabajook3').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('lugarok1').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('lugarok2').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('lugarok3').style.backgroundColor = 'rgb(80, 80, 255)';
    document.getElementById('puestook1').style.backgroundColor = 'rgb(130, 130, 255)';
    document.getElementById('puestook2').style.backgroundColor = 'rgb(130, 130, 255)';
    document.getElementById('puestook3').style.backgroundColor = 'rgb(130, 130, 255)';
    document.getElementById('contenedorResultado').style.backgroundColor = 'rgb(200, 200, 255)';
});
